Add GitHub workflows 'lint' and 'build'
cloud-barista/cb-operator pull request #98
Opened 2021-01-05 04:55 UTC by jihoon-seo

- (이 PR의 Reviewers 로 @hermitkim1 님도 추가하려고 했는데, 추가가 안 되네요.. :(
GitHub 의 문제/이슈로 보입니다.)
![image](https://user-images.githubusercontent.com/46767780/103607328-fa023900-4f5b-11eb-9b9e-a8e63300d2ab.png)

- GitHub workflows 'lint' and 'build' YAML files by @hermitkim1
  - https://github.com/hermitkim1/golang-ci-demo-by-github-actions#lint
- GitHub Lint action 실행 시 내부적으로 `golangci-lint` 가 실행되는데, `--out-format=github-actions` 옵션이 붙어서 실행되어,
GitHub 웹 인터페이스에서는 어느 파일의 어느 라인이 문제인지 알 수가 없습니다. [[링크]](https://github.com/jihoon-seo/cb-operator/runs/1642201369?check_suite_focus=true)
![image](https://user-images.githubusercontent.com/46767780/103607565-8f9dc880-4f5c-11eb-9e6d-3faf43acad7e.png)
  - 시도 1: 개발 VM에 `golint` 를 설치하고 실행하여 표시되는 사항들을 모두 수정했으나, GitHub Lint action 의 `golangci-lint` 는 여전히 에러가 1개 있다고 표시했습니다.
  - 시도 2: 개발 VM에 `golangci-lint` 를 설치하고 실행하여 표시되는 사항들을 모두 수정했더니, GitHub Lint action 도 통과했습니다.
  - 추가 시도: GitHub Lint action 실행 시 `--out-format=github-actions` 옵션을 뺄 수 있을까 했는데, `lint-on-push.yml` 파일에는 해당 구문이 없습니다.

2021-01-05 05:00 UTC, jihoon-seo commented
PR 을 올리고 나서 보니, CamelCase 에서 대소문자 일관성이 떨어지는 부분이 있습니다.

- "Cb"
  - CbOperatorMode
- "CB"
  - CBK8sNamespace
  - CBHelmReleaseName

2021-01-05 05:27 UTC, hermitkim1 commented
@jihoon-seo 

빠르게 적용하고 계시네요 ㅎㅎ

감사하면서도 아직 미흡한 부분으로 인한 에러로 죄송하기도 합니다. ㅠㅠ
(현재로서는 cloud-barista/cb-operator에 바로 적용하시기 보다 Fork하여 테스트 해보시는것을 추천 드립니다.)


말씀하신 에러에 대한 파일명과 라인번호 표기는 꼭 필요한 사항입니다.

저도 테스트시 [Staticcheck's Checks](https://staticcheck.io/docs/checks)를 참고하여 "시도 2"와 같은 방법으로 해결한 후 진행하지 못하고 있던 부분 입니다.

이슈로 등록하였고요. 업데이트 하도록 하겠습니다.

2021-01-05 06:01 UTC, hermitkim1 commented
참고로, [golangci-lint-action의 이슈 #119](https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-738355857)에서 `::` Syntax를 활용하여 파일명과 라인번호를 기재하였고, 이로 이 github actions에서 정보를 보여주고 있지 않다고 합니다.

2021-01-05 06:10 UTC, seokho-son commented
@cloud-barista/cb-operator-maintainer 팀을 만들고
cb-operator 저장소 maintainer 권한을 추가하였습니다.
(https://github.com/orgs/cloud-barista/teams/cb-operator-maintainer , @hermitkim1 환영 합니다..^^)

2021-01-05 07:30 UTC, hermitkim1 requested changes
**`lint-on-push.yml` 수행 시 에러에 대한 "파일명"과 "라인번호" 미출력 문제 해결 방안**

현재는 steps 부분을 아래와 같이 수정하시면 파일명과 라인번호 확인 하실 수 있습니다.

CB-Larva에서 테스트 완료 하였고요.

GitHub Actions와 golangci-lint에서 관련 이슈를 얼른 해결하기를 바래봅니다. 😄 

변경안
```yaml
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1      
    
    - name: Run golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run
```
옵션도 적용 가능합니다.  옵션은 [여기](https://golangci-lint.run/usage/configuration/)를 참고 바랍니다.

예) 
- $(go env GOPATH)/bin/golangci-lint run --skip-dirs poc-cb-net/archive
- $(go env GOPATH)/bin/golangci-lint run --out-format=line-number

변경전
```yaml
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29

        # Add args to skip dirs
        #args: --skip-dirs mypath

        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true 
```

2021-01-05 08:02 UTC, jihoon-seo commented
@hermitkim1 알려주신 대로 수정했습니다. 감사합니다!

2021-01-05 08:08 UTC, hermitkim1 approved these changes

2021-01-07 02:46 UTC, seokho-son commented
LGTM

2021-01-07 02:46 UTC, merged